Update BullLogger.java
bullbots/BullBotsLib pull request #4
Opened 2023-03-17 01:36 UTC by CodeLikeAGecko

Various fixes and updates pulled in from season code.

2023-03-17 15:09 UTC, StephenDay1 requested changes

2023-03-17 15:09 UTC, StephenDay1 commented on src/main/java/frc/team1891/common/logger/BullLogger.java
> +        if (Robot.isReal()) {
Since this is a library, the Robot.java file isn't accessible, as it's part of each individual project this would be imported into.  
I don't know what the workaround would have to be, but we'd need to check this some other way.

2023-03-17 15:09 UTC, StephenDay1 commented on src/main/java/frc/team1891/common/logger/BullLogger.java
> +    }
First, is there a reason it's LogException instead of logException? Just a small thing that confused me.
And then instead of `System.out.println();`, you could use `DriverStation.reportWarning();`.  It's not necessary, but it might be better.

2023-03-17 15:09 UTC, StephenDay1 commented on src/main/java/frc/team1891/common/logger/BullLogger.java
> +        if (Robot.isReal()) {
Maybe you could check the deploy directory and make sure it's the path that the roborio would have instead of some user's desktop path? `FileSystem.getDeployDirectory()`

2023-03-17 17:22 UTC, StephenDay1 commented on src/main/java/frc/team1891/common/logger/BullLogger.java
> +        if (Robot.isReal()) {
After looking at how `getDeployDirectory()` works, it turns out it actually calls `RobotBase.isReal()`.  So even though `Robot.java` isn't accessible, `RobotBase` is.

2023-03-18 16:47 UTC, CodeLikeAGecko commented on src/main/java/frc/team1891/common/logger/BullLogger.java
> +    }
Fixed both these issues in the 2nd commit.

2023-03-18 16:59 UTC, CodeLikeAGecko commented on src/main/java/frc/team1891/common/logger/BullLogger.java
> +        if (Robot.isReal()) {
Updated to use RobotBase.isReal(). Not changing the usb directory determination since that pattern was lifted from the FRC logger code.

2023-03-18 17:03 UTC, StephenDay1 approved these changes

2023-03-18 17:04 UTC, StephenDay1 commented
Thanks for your work on this!

2023-03-18 17:04 UTC, merged